name: breast-cancer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core Data Science Libraries
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Machine Learning Libraries
  - scikit-learn>=1.1.0
  - joblib>=1.1.0

  # Jupyter Notebook Support
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.4.0

  # Data Processing
  - scipy>=1.9.0

  # Development Tools
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=4.0.0

  # Optional: For enhanced performance
  - numba>=0.56.0

  # Additional packages via pip
  - pip
  - pip:
      - plotly>=5.0.0
